DROP VIEW IF EXISTS MONTHLY_SALE;

CREATE VIEW MONTHLY_SALE AS
SELECT
    ID            AS SALE_ID,
    BOOK_ID       AS BOOK_ID,
    PUBLISHING_ID AS PUBLISHING_ID,
    SALE_YEAR     AS SALE_YEAR,
    SALE_MONTH    AS SALE_MONTH,
    QUANTITY_SOLD AS QUANTITY_SOLD,
    QUANTITY_RETURN AS QUANTITY_RETURN,
    AVERAGE_DISCOUNT AS AVERAGE_DISCOUNT
FROM BOOK_SALES;